services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment: 
      - .env

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
          VITE_BACKEND_ENDPOINT: http://localhost:5000
          VITE_SERVER_HOSTNAME: ${HOSTNAME}
    ports:
      - 3000:3000
    depends_on:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodbdata:

