- name: Setup backend
  hosts: backend
  become: true

  tasks:
    - name: Remove existing backend directory (if any)
      file:
        path: /home/ubuntu/app
        state: absent

    - name: Clone backend repo
      git:
        repo: https://github.com/kengoestech/mern-gallery-sample-app.git
        dest: /home/ubuntu/app
        version: main

    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repo
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Install Docker and Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    # - name: Copy backend-compose.yml file
    #   copy:
    #     src: /home/kennedy_salud/mern-gallery-sample-app/ansible/backend-compose.yml
    #     dest: /home/ubuntu/backend
    #     owner: ubuntu
    #     mode: '0644'

    - name: Copy .env file
      copy:
        src: /home/kennedy_salud/mern-gallery-sample-app/backend/.env
        dest: /home/ubuntu/app/ansible/.env
        owner: ubuntu
        mode: '0644'

    - name: Run docker compose up
      command: docker compose -f ../ansible/backend-compose.yml up -d --build
      args:
        chdir: /home/ubuntu/app/backend/