services:
  frontend:
    build:
      context: /home/ubuntu/app/frontend
      dockerfile: Dockerfile
      args:
          VITE_BACKEND_ENDPOINT: http://private-lb-fp-2192c959af4e2737.elb.us-east-1.amazonaws.com:5000
          VITE_SERVER_HOSTNAME: ${HOSTNAME}
    ports:
      - 3000:3000
