- name: Setup frontend
  hosts: frontend
  become: true

  tasks:

    - name: Clone from git repository
      ansible.builtin.git:
        repo: 'https://github.com/kengoestech/mern-gallery-sample-app.git'
        clone: true
        version: main
        dest: /home/ubuntu/app

    - name: Install Docker inside frontend instance
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Build Frontend Docker Image
      community.docker.docker_image:
        name: frontend-app
        tag: latest
        path: /home/ubuntu/app/frontend
        args:
          VITE_BACKEND_ENDPOINT: "http://private-lb-fp-0b9ecc188b2812db.elb.us-east-1.amazonaws.com:5000"
          VITE_SERVER_HOSTNAME: "your-hostname"

    - name: Run Container Image
      community.docker.docker_container:
        name: frontend-app
        image: frontend-app:latest
        state: started
        published_ports:
          - "3000:3000"
