version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"
    environment:
      - .env

volumes:
  mongodbdata: