- name: Setup MongoDB
  hosts: mongodb
  become: true

  tasks:
    - name: Add MongoDB GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present

    - name: Add MongoDB repo
      apt_repository:
        repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse"
        state: present
        filename: mongodb-org

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes