- name: Setup MongoDB
  hosts: mongodb
  become: yes
  tasks:

    - name: Remove existing backend directory (if any)
      file:
        path: /home/ubuntu/app
        state: absent

    - name: Clone mongodb repo
      git:
        repo: https://github.com/kengoestech/mern-gallery-sample-app.git
        dest: /home/ubuntu/app
        version: main

    - name: Install required system packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repo
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Install Docker and Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Run docker compose up
      command: docker compose -f /home/ubuntu/app/ansible/mongo-compose.yml up -d --build

