name: Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: shivammathur/setup-ansible@v1
        with:
          ansible_version: '2.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run MongoDB Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory mongodb.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Backend Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory backend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Frontend Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory frontend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
