name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Specify the Terraform version you want to use

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

  ansible:
    runs-on: ubuntu-latest
    needs: terraform  # Ensures Ansible runs after Terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: shivammathur/setup-ansible@v1
        with:
          ansible_version: '2.10'  # Specify the Ansible version you want to use

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt  # If you have a requirements.txt

      - name: Run MongoDB Ansible Playbook
        run: ansible-playbook -i inventory mongodb.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking if required

      - name: Run Backend Ansible Playbook
        run: ansible-playbook -i inventory backend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking if required

      - name: Run Frontend Ansible Playbook
        run: ansible-playbook -i inventory frontend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"  # Disable host key checking if required
