name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  

      - name: List files in the repository (Debugging Step)
        run: |
          echo "Listing files in the root directory:"
          ls -al 

      - name: List files in the mern-gallery-sample-app directory (Debugging Step)
        run: |
          echo "Listing files in the mern-gallery-sample-app directory:"
          ls -al terraform

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Run Terraform Init, Plan, and Apply
        run: |
          cd terraform  # Change to the correct directory
          terraform init  # Initialize Terraform
          terraform plan   # Run Terraform plan
          terraform apply -auto-approve  # Apply the changes

  
