name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls -al  # Verify the repository's file structure

      - name: List files in the terraform directory
        run: ls -al kengoestech/mern-gallery-sample-app/terraform  # Ensure `main.tf` exists

      - name: Change to Terraform Directory
        run: cd kengoestech/mern-gallery-sample-app/terraform  # Change directory to where `main.tf` is located

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Initialize Terraform
        run: terraform init  # Initialize Terraform

      - name: Plan Terraform
        run: terraform plan -out=tfplan  # Run terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan  # Apply the changes

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: shivammathur/setup-ansible@v1
        with:
          ansible_version: '2.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run MongoDB Ansible Playbook
        run: ansible-playbook -i inventory/hosts mongodb.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Backend Ansible Playbook
        run: ansible-playbook -i inventory/hosts backend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Frontend Ansible Playbook
        run: ansible-playbook -i inventory/hosts frontend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
