name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  

      - name: List files in the repository (Debugging Step)
        run: |
          echo "Listing files in the root directory:"
          ls -al 

      - name: List files in the mern-gallery-sample-app directory (Debugging Step)
        run: |
          echo "Listing files in the mern-gallery-sample-app directory:"
          ls -al terraform

      - name: Run Terraform Init, Plan, and Apply
        run: |
          cd terraform  
          terraform init  # Initialize Terraform
          terraform plan -out=tfplan  # Run Terraform plan
          terraform apply -auto-approve tfplan  # Apply the Terraform changes

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: shivammathur/setup-ansible@v1
        with:
          ansible_version: '2.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run MongoDB Ansible Playbook
        run: ansible-playbook -i inventory mongodb.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Backend Ansible Playbook
        run: ansible-playbook -i inventory backend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Frontend Ansible Playbook
        run: ansible-playbook -i inventory frontend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
