name: Terraform and Ansible Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: ls -al  # Verify your directory structure

      - name: Change Directory to Terraform Folder
        run: cd kengoestech/mern-gallery-sample-app/terraform  # Change to correct directory
        continue-on-error: true  # Optional, allows workflow to continue even if this step fails

      - name: Verify Directory Exists
        run: ls -al kengoestech/mern-gallery-sample-app/terraform  # List contents of the specific directory to confirm

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: shivammathur/setup-ansible@v1
        with:
          ansible_version: '2.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run MongoDB Ansible Playbook
        run: ansible-playbook -i inventory/hosts mongodb.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Backend Ansible Playbook
        run: ansible-playbook -i inventory/hosts backend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"

      - name: Run Frontend Ansible Playbook
        run: ansible-playbook -i inventory/hosts frontend.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
